version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

root: #默認情況下配置
    level: DEBUG
    handlers:
        [console, debug_file_handler, info_file_handler, error_file_handler]

loggers: #如果有設定loggers的話會採用，否則採用root設定
    logger1:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    debug_file_handler:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: logs/debug.log
        mode: w
        encoding: utf8
    info_file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: logs/infos.log
        mode: w
        encoding: utf8
    error_file_handler:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        mode: w
        encoding: utf8
